
package Httpcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyJMSWS", targetNamespace = "http://tcleyman/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyJMSWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://tcleyman/", className = "Httpcode.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://tcleyman/", className = "Httpcode.SayHelloResponse")
    @Action(input = "http://tcleyman/MyJMSWS/sayHelloRequest", output = "http://tcleyman/MyJMSWS/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello2", targetNamespace = "http://tcleyman/", className = "Httpcode.SayHello2")
    @ResponseWrapper(localName = "sayHello2Response", targetNamespace = "http://tcleyman/", className = "Httpcode.SayHello2Response")
    @Action(input = "http://tcleyman/MyJMSWS/sayHello2Request", output = "http://tcleyman/MyJMSWS/sayHello2Response")
    public String sayHello2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
